code_generation_task:
  description: >
    Generate complete Python code with these features:
    1. Read dataset.csv
    2. Data transformations from plan
    3. Plot generation with matplotlib/seaborn
    4. Save plot to file
    
    The code MUST:
    - Include all necessary imports
    - Include type annotations
    - Save generated plot as plot.png
    - Output success/error messages
    - Be ready to run. No additional text. Only code.
  expected_output: >
    A complete Python script (grafica.py) that:
    - Performs necessary data transformations
    - Generates professional visualizations
    - Handles errors gracefully
    - Saves both the plot and the code
    - Is ready to run
  agent: code_writer_agent
